import type { GraphEdge, GraphNode, HarnessProject, LayoutNode, SkillFile } from './types';

function hasAny(text: string, terms: string[]): boolean {
  return terms.some((term) => text.includes(term));
}

function createSkill(prompt: string, name: string): SkillFile {
  return {
    id: 'skill-main',
    name: `${name}-skill`,
    description: 'Generated primary skill',
    content: `---\nname: ${name}-skill\ndescription: Generated by Harness Editor\n---\n\n# ${name}\n\nUser intent: ${prompt}\n\n## Behavior\n- Generate a working harness skeleton from intent\n- Preserve safety boundaries\n- Emit trace-friendly execution output\n`
  };
}

export function generateHarnessProject(name: string, prompt: string): HarnessProject {
  const normalized = prompt.toLowerCase();
  const nodes: GraphNode[] = [
    { id: 'session-start', kind: 'SessionStart', label: 'Session Start' },
    { id: 'user-submit', kind: 'UserPromptSubmit', label: 'User Prompt Submit' },
    { id: 'main-skill', kind: 'Skill', label: 'Generate Harness Skeleton', config: { skillId: 'skill-main' } },
    { id: 'sequence-main', kind: 'Sequence', label: 'Primary Flow' },
    { id: 'stop', kind: 'Stop', label: 'Stop' }
  ];

  if (hasAny(normalized, ['approval', 'approve', 'permission', '권한', '승인'])) {
    nodes.push({ id: 'permission-gate', kind: 'Permission', label: 'Permission Gate' });
  }
  if (hasAny(normalized, ['mcp', 'server', 'tool', '도구', '서버'])) {
    nodes.push({ id: 'mcp-server', kind: 'MCPServer', label: 'MCP Server Registration' });
  }
  if (hasAny(normalized, ['retry', 'loop', 'review', '검토', '반복'])) {
    nodes.push({ id: 'review-loop', kind: 'Loop', label: 'Review Loop' });
  }
  if (hasAny(normalized, ['state', 'memory', '기억', '상태'])) {
    nodes.push({ id: 'state-write', kind: 'StateWrite', label: 'Persist State' });
  }
  if (hasAny(normalized, ['custom', 'novel', 'opaque', '새로운', '신규'])) {
    nodes.push({ id: 'custom-block', kind: 'CustomBlock', label: 'Novel Runtime Block' });
  }

  const edges: GraphEdge[] = [];
  const order = nodes.map((node) => node.id);
  for (let i = 0; i < order.length - 1; i += 1) {
    edges.push({ id: `edge-${i}`, from: order[i], to: order[i + 1] });
  }

  const layout: LayoutNode[] = nodes.map((node, index) => ({
    id: node.id,
    x: 80 + index * 180,
    y: index % 2 === 0 ? 120 : 260
  }));

  const skill = createSkill(prompt, name);

  return {
    manifest: {
      name,
      version: '0.1.0',
      description: `Harness project for: ${prompt}`,
      targetRuntime: 'claude-code',
      createdAt: new Date().toISOString(),
      prompt
    },
    nodes,
    edges,
    skills: [skill],
    layout
  };
}
