import { COMPOSITE_PATTERNS, createRegistrySnapshot } from './registry';
import type {
  AuthoringDecision,
  CompositeInstance,
  ConfirmationRequest,
  CustomBlockDefinition,
  GraphEdge,
  GraphNode,
  HarnessProject,
  LayoutNode,
  SkillFile
} from './types';

function hasAny(text: string, terms: string[]): boolean {
  return terms.some((term) => text.includes(term));
}

function createSkill(prompt: string, name: string, warnings: string[]): SkillFile {
  const warningSection =
    warnings.length === 0
      ? '- Use safe defaults when a user request is ambiguous\n'
      : warnings.map((warning) => `- ${warning}`).join('\n');

  return {
    id: 'skill-main',
    name: `${name}-skill`,
    description: 'Generated primary skill',
    content: `---\nname: ${name}-skill\ndescription: Generated by Harness Editor\n---\n\n# ${name}\n\nUser intent: ${prompt}\n\n## Behavior\n- Generate a working harness skeleton from intent\n- Preserve safety boundaries\n- Emit trace-friendly execution output\n\n## Safety notes\n${warningSection}\n`
  };
}

function detectConfirmationRequests(normalized: string): ConfirmationRequest[] {
  const requests: ConfirmationRequest[] = [];

  if (hasAny(normalized, ['sudo', 'full access', 'all permissions', 'network access', 'filesystem access', 'shell access'])) {
    requests.push({
      id: 'confirm-risk-permissions',
      kind: 'risk-bearing-permission',
      reason: 'Request adds permissions beyond the default safe scaffold.',
      message: 'Confirm enabling elevated runtime or tool permissions for the generated harness.',
      confirmed: false
    });
  }

  if (hasAny(normalized, ['bypass safety', 'disable guardrail', 'ignore policy', 'skip approval', 'override safety'])) {
    requests.push({
      id: 'confirm-safety-policy',
      kind: 'safety-policy-change',
      reason: 'Request weakens or changes safety guardrails.',
      message: 'Confirm the harness may weaken or reinterpret an existing safety boundary.',
      confirmed: false
    });
  }

  if (hasAny(normalized, ['delete files', 'rm -rf', 'drop database', 'destroy data', 'wipe workspace'])) {
    requests.push({
      id: 'confirm-destructive-runtime',
      kind: 'destructive-runtime',
      reason: 'Request enables destructive runtime behavior.',
      message: 'Confirm the harness may perform destructive operations during execution.',
      confirmed: false
    });
  }

  return requests;
}

function createAuthoringDecision(
  prompt: string,
  nodes: GraphNode[],
  confirmationRequests: ConfirmationRequest[],
  customBlocks: CustomBlockDefinition[]
): AuthoringDecision {
  const warnings = [
    'Layout is stored separately from semantic graph data.',
    'Generated harness targets Claude Code for Phase 0 only.',
    ...confirmationRequests.map((request) => request.message),
    ...(customBlocks.length > 0 ? ['Custom blocks are opaque and must be traced at runtime.'] : [])
  ];

  const traceIntent = ['hook-activation', 'branch-selection', 'state-transition'];
  if (nodes.some((node) => node.kind === 'Loop')) traceIntent.push('loop-iteration');
  if (customBlocks.length > 0) traceIntent.push('custom-block');

  return {
    summary: `Generate a Claude Code-native harness project for: ${prompt}`,
    warnings,
    confirmationRequests,
    compatibleRuntimes: ['claude-code'],
    traceIntent
  };
}

function createCustomBlockDefinitions(normalized: string): CustomBlockDefinition[] {
  if (!hasAny(normalized, ['custom', 'novel', 'opaque', '새로운', '신규'])) {
    return [];
  }

  return [
    {
      id: 'custom-block-main',
      label: 'Novel Runtime Block',
      description: 'Opaque AI-generated runtime logic that participates in compile and trace flows.',
      opaque: true,
      ports: [
        { id: 'in', label: 'In', direction: 'input' },
        { id: 'out', label: 'Out', direction: 'output' }
      ]
    }
  ];
}

function createCompositeInstances(nodes: GraphNode[], customBlocks: CustomBlockDefinition[]): CompositeInstance[] {
  const nodeIds = new Set(nodes.map((node) => node.id));
  const composites: CompositeInstance[] = [];

  const addComposite = (patternId: string, label: string, expandedNodeIds: string[]) => {
    const pattern = COMPOSITE_PATTERNS.find((item) => item.id === patternId);
    if (!pattern) return;
    composites.push({
      id: `${patternId}-instance`,
      patternId,
      label,
      expandedNodeIds: expandedNodeIds.filter((nodeId) => nodeIds.has(nodeId))
    });
  };

  if (nodeIds.has('permission-gate')) {
    addComposite('permission-gate', 'Permission Gate', ['permission-gate', 'main-skill', 'state-write']);
  }
  if (nodeIds.has('review-loop')) {
    addComposite('review-loop', 'Review Loop', ['main-skill', 'review-loop', 'state-write']);
    addComposite('ralph-loop', 'Ralph Loop', ['review-loop', 'state-write', 'post-tool-use']);
  }
  if (nodeIds.has('session-start') && nodeIds.has('system-prompt')) {
    addComposite('session-init-bundle', 'Session Init Bundle', ['session-start', 'system-prompt', 'state-write']);
  }
  if (nodeIds.has('mcp-server')) {
    addComposite('mcp-registration', '3-Tier MCP Registration', ['permission-gate', 'mcp-server', 'post-tool-use']);
  }
  if (nodeIds.has('state-write')) {
    addComposite('lore-memory-persist', 'Lore/Memory Persist', ['main-skill', 'state-write', 'post-tool-use']);
  }
  if (customBlocks.length > 0) {
    addComposite('evolutionary-seed', 'Evolutionary Seed', ['custom-block', 'main-skill', 'post-tool-use']);
  }

  return composites;
}

export function applyRiskConfirmations(project: HarnessProject, confirmed: boolean): HarnessProject {
  return {
    ...project,
    authoring: {
      ...project.authoring,
      confirmationRequests: project.authoring.confirmationRequests.map((request) => ({
        ...request,
        confirmed
      }))
    }
  };
}

function pushNode(nodes: GraphNode[], kind: GraphNode['kind'], label: string, config?: Record<string, unknown>) {
  const id = `${kind.toLowerCase()}-${nodes.length + 1}`;
  nodes.push({ id, kind, label, config });
  return id;
}

function attach(nodes: GraphNode[], edges: GraphEdge[], from: string, to: string, label?: string) {
  edges.push({ id: `edge-${edges.length + 1}`, from, to, label });
}

function createConfirmationRequests(normalized: string): ConfirmationRequest[] {
  const requests: ConfirmationRequest[] = [];
  if (hasAny(normalized, ['permission', 'approve', 'approval', '권한', '승인'])) {
    requests.push({
      id: 'confirm-permission-gate',
      kind: 'risk-bearing-permission',
      reason: 'Prompt implies a risky permission or approval boundary.',
      message: 'Confirm the permission or approval policy before emitting the final runtime package.',
      confirmed: false
    });
  }
  if (hasAny(normalized, ['delete', 'destroy', 'reset', 'drop', '파괴', '삭제'])) {
    requests.push({
      id: 'confirm-destructive-runtime',
      kind: 'destructive-runtime',
      reason: 'Prompt implies destructive runtime behavior.',
      message: 'Confirm destructive runtime behavior before compiling runnable hooks.',
      confirmed: false
    });
  }
  return requests;
}

function selectCompositeInstances(nodes: GraphNode[], normalized: string): CompositeInstance[] {
  const wanted = new Set<string>(['session-init-bundle']);
  if (hasAny(normalized, ['approval', 'approve', 'permission', '권한', '승인'])) wanted.add('permission-gate');
  if (hasAny(normalized, ['retry', 'loop', 'review', '검토', '반복'])) wanted.add('review-loop');
  if (hasAny(normalized, ['mcp', 'server', 'tool', '도구', '서버'])) wanted.add('mcp-registration');
  if (hasAny(normalized, ['memory', 'state', '상태', '기억'])) wanted.add('lore-memory-persist');
  if (hasAny(normalized, ['custom', 'novel', 'opaque', '새로운', '신규'])) wanted.add('evolutionary-seed');

  return COMPOSITE_PATTERNS.filter((pattern) => wanted.has(pattern.id)).map((pattern, index) => ({
    id: `composite-${index + 1}`,
    patternId: pattern.id,
    label: pattern.name,
    expandedNodeIds: nodes.filter((node) => pattern.includes.includes(node.kind)).map((node) => node.id)
  }));
}

function createCustomBlocks(normalized: string): CustomBlockDefinition[] {
  if (!hasAny(normalized, ['custom', 'novel', 'opaque', '새로운', '신규', 'runtime'])) {
    return [];
  }
  return [
    {
      id: 'custom-runtime-1',
      label: 'Novel Runtime Block',
      description: 'Opaque runtime generation block for novel hook/runtime logic',
      opaque: true,
      ports: [
        { id: 'intent-in', label: 'Intent', direction: 'input' },
        { id: 'runtime-out', label: 'Runtime', direction: 'output' }
      ]
    }
  ];
}

function createAuthoringDecision(prompt: string, normalized: string, confirmationRequests: ConfirmationRequest[]): AuthoringDecision {
  const warnings: string[] = [];
  if (confirmationRequests.length > 0) warnings.push('Risk-sensitive operations require confirmation before final export.');
  if (hasAny(normalized, ['novel', 'new runtime', '새로운', '신규'])) warnings.push('Novel runtime generation should be validated against representative E2E scenarios.');

  const traceIntent: TraceEvent['eventType'][] = ['hook-activation', 'state-transition'];
  if (hasAny(normalized, ['review', 'loop', 'retry', '검토', '반복'])) traceIntent.push('loop-iteration');
  if (hasAny(normalized, ['condition', 'branch', 'if', '분기'])) traceIntent.push('branch-selection');
  if (hasAny(normalized, ['custom', 'opaque', 'novel', '새로운'])) traceIntent.push('custom-block');
  if (hasAny(normalized, ['mcp', 'server'])) traceIntent.push('mcp-server');
  traceIntent.push('failure');

  return {
    summary: `Generate a Claude Code harness for: ${prompt}`,
    warnings,
    confirmationRequests,
    compatibleRuntimes: ['claude-code', 'opencode', 'codex'],
    traceIntent
  };
}

export function generateHarnessProject(name: string, prompt: string): HarnessProject {
  const normalized = prompt.toLowerCase();
  const customBlocks = createCustomBlockDefinitions(normalized);
  const confirmationRequests = detectConfirmationRequests(normalized);

  const nodes: GraphNode[] = [
    { id: 'session-start', kind: 'SessionStart', label: 'Session Start' },
    { id: 'system-prompt', kind: 'SystemPrompt', label: 'System Prompt Guardrails' },
    { id: 'user-submit', kind: 'UserPromptSubmit', label: 'User Prompt Submit' },
    { id: 'sequence-main', kind: 'Sequence', label: 'Primary Flow' },
    { id: 'pre-tool-use', kind: 'PreToolUse', label: 'Pre Tool Use' },
    { id: 'main-skill', kind: 'Skill', label: 'Generate Harness Skeleton', config: { skillId: 'skill-main' } }
  ];

  if (hasAny(normalized, ['approval', 'approve', 'permission', '권한', '승인'])) {
    const permissionId = pushNode(nodes, 'Permission', 'Permission Gate');
    attach(nodes, edges, mainSkill, permissionId, 'requires-review');
    attach(nodes, edges, permissionId, sequence, 'approved');
  }
  if (hasAny(normalized, ['mcp', 'server', 'tool', '도구', '서버'])) {
    const mcpId = pushNode(nodes, 'MCPServer', 'MCP Server Registration');
    attach(nodes, edges, sequence, mcpId, 'register-mcp');
    attach(nodes, edges, mcpId, stop, 'ready');
  }
  if (hasAny(normalized, ['retry', 'loop', 'review', '검토', '반복'])) {
    const loopId = pushNode(nodes, 'Loop', 'Review Loop');
    attach(nodes, edges, sequence, loopId, 'review');
    attach(nodes, edges, loopId, sequence, 'retry');
  }
  if (hasAny(normalized, ['state', 'memory', '기억', '상태'])) {
    nodes.push({ id: 'state-read', kind: 'StateRead', label: 'Read Existing State' });
  }
  if (customBlocks.length > 0) {
    nodes.push({
      id: 'custom-block',
      kind: 'CustomBlock',
      label: 'Novel Runtime Block',
      config: { customBlockId: customBlocks[0].id }
    });
  }

  nodes.push(
    { id: 'state-write', kind: 'StateWrite', label: 'Persist State' },
    { id: 'post-tool-use', kind: 'PostToolUse', label: 'Post Tool Use' },
    { id: 'stop', kind: 'Stop', label: 'Stop' }
  );

  const edges: GraphEdge[] = [];
  const order = nodes.map((node) => node.id);
  for (let index = 0; index < order.length - 1; index += 1) {
    edges.push({ id: `edge-${index}`, from: order[index], to: order[index + 1] });
  }

  const layout: LayoutNode[] = nodes.map((node, index) => ({
    id: node.id,
    x: 80 + (index % 4) * 220,
    y: 120 + Math.floor(index / 4) * 160
  }));

  const authoring = createAuthoringDecision(prompt, nodes, confirmationRequests, customBlocks);
  const skill = createSkill(prompt, name, authoring.warnings);

  return {
    manifest: {
      name,
      version: '0.1.0',
      description: `Harness project for: ${prompt}`,
      targetRuntime: 'claude-code',
      createdAt: new Date().toISOString(),
      prompt
    },
    nodes,
    edges,
    skills: [skill],
    layout,
    composites: createCompositeInstances(nodes, customBlocks),
    customBlocks,
    registry: createRegistrySnapshot(),
    authoring
  };
}
