import { COMPOSITE_PATTERNS, createRegistrySnapshot } from './registry';
import { describeRuntimeTarget } from './runtime-targets';
import type {
  AuthoringDecision,
  CompositeInstance,
  ConfirmationRequest,
  CustomBlockDefinition,
  GraphEdge,
  GraphNode,
  HarnessProject,
  LayoutNode,
  SkillFile,
  TraceEvent,
  RuntimeTarget
} from './types';

function hasAny(text: string, terms: string[]): boolean {
  return terms.some((term) => text.includes(term));
}

function createSkill(prompt: string, name: string, warnings: string[], targetRuntime: RuntimeTarget): SkillFile {
  const runtime = describeRuntimeTarget(targetRuntime);
  const warningSection =
    warnings.length === 0
      ? '- Use safe defaults when a user request is ambiguous\n'
      : warnings.map((warning) => `- ${warning}`).join('\n');

  return {
    id: 'skill-main',
    name: `${name}-skill`,
    description: 'Generated primary skill',
    content: `---\nname: ${name}-skill\ndescription: Generated by oh-my-openharness for ${runtime.authoringNoun}\n---\n\n# ${name}\n\nUser intent: ${prompt}\n\n## Target runtime\n- ${runtime.authoringNoun}\n\n## Behavior\n- Generate a working harness skeleton from intent\n- Preserve safety boundaries\n- Keep runtime choice explicit before writing runtime-specific artifacts\n- Emit trace-friendly execution output\n\n## Safety notes\n${warningSection}\n`
  };
}

function createCustomBlocks(normalized: string): CustomBlockDefinition[] {
  if (!hasAny(normalized, ['custom', 'novel', 'opaque', '새로운', '신규', 'runtime'])) {
    return [];
  }
  return [
    {
      id: 'custom-runtime-1',
      label: 'Novel Runtime Block',
      description: 'Opaque runtime generation block for novel hook/runtime logic',
      opaque: true,
      ports: [
        { id: 'intent-in', label: 'Intent', direction: 'input' },
        { id: 'runtime-out', label: 'Runtime', direction: 'output' }
      ]
    }
  ];
}

function detectConfirmationRequests(normalized: string): ConfirmationRequest[] {
  const requests: ConfirmationRequest[] = [];

  if (hasAny(normalized, ['sudo', 'full access', 'all permissions', 'network access', 'filesystem access', 'shell access', 'permission', 'approve', 'approval', '권한', '승인'])) {
    requests.push({
      id: 'confirm-risk-permissions',
      kind: 'risk-bearing-permission',
      reason: 'Request adds permissions beyond the default safe scaffold.',
      message: 'Confirm enabling elevated runtime or tool permissions for the generated harness.',
      confirmed: false
    });
  }

  if (hasAny(normalized, ['bypass safety', 'disable guardrail', 'ignore policy', 'skip approval', 'override safety'])) {
    requests.push({
      id: 'confirm-safety-policy',
      kind: 'safety-policy-change',
      reason: 'Request weakens or changes safety guardrails.',
      message: 'Confirm the harness may weaken or reinterpret an existing safety boundary.',
      confirmed: false
    });
  }

  if (hasAny(normalized, ['delete', 'destroy', 'reset', 'drop', 'rm -rf', 'wipe workspace', '파괴', '삭제'])) {
    requests.push({
      id: 'confirm-destructive-runtime',
      kind: 'destructive-runtime',
      reason: 'Request enables destructive runtime behavior.',
      message: 'Confirm the harness may perform destructive operations during execution.',
      confirmed: false
    });
  }

  return requests;
}

function createAuthoringDecision(
  prompt: string,
  nodes: GraphNode[],
  confirmationRequests: ConfirmationRequest[],
  customBlocks: CustomBlockDefinition[],
  targetRuntime: RuntimeTarget
): AuthoringDecision {
  const runtime = describeRuntimeTarget(targetRuntime);
  const warnings = [
    'Layout is stored separately from semantic graph data.',
    `Generated harness targets ${runtime.authoringNoun} for the current authoring lane.`,
    ...confirmationRequests.map((request) => request.message),
    ...(customBlocks.length > 0 ? ['Custom blocks are opaque and must be traced at runtime.'] : [])
  ];

  const traceIntent: TraceEvent['eventType'][] = ['hook-activation', 'state-transition'];
  if (nodes.some((node) => node.kind === 'Permission')) traceIntent.push('branch-selection');
  if (nodes.some((node) => node.kind === 'Loop')) traceIntent.push('loop-iteration');
  if (customBlocks.length > 0) traceIntent.push('custom-block');
  if (nodes.some((node) => node.kind === 'MCPServer')) traceIntent.push('mcp-server');
  traceIntent.push('failure');

  return {
    summary: `Generate a ${runtime.authoringNoun}-native harness project for: ${prompt}`,
    warnings,
    confirmationRequests,
    compatibleRuntimes: [targetRuntime],
    traceIntent
  };
}

function createCompositeInstances(nodes: GraphNode[], customBlocks: CustomBlockDefinition[]): CompositeInstance[] {
  const nodeIds = new Set(nodes.map((node) => node.id));
  const composites: CompositeInstance[] = [];

  const addComposite = (patternId: string, label: string, expandedNodeIds: string[]) => {
    const pattern = COMPOSITE_PATTERNS.find((item) => item.id === patternId);
    if (!pattern) return;
    composites.push({
      id: `${patternId}-instance`,
      patternId,
      label,
      expandedNodeIds: expandedNodeIds.filter((nodeId) => nodeIds.has(nodeId))
    });
  };

  if (nodeIds.has('session-start') && nodeIds.has('system-prompt') && nodeIds.has('state-write')) {
    addComposite('session-init-bundle', 'Session Init Bundle', ['session-start', 'system-prompt', 'state-write']);
  }
  if (nodeIds.has('permission-gate')) {
    addComposite('permission-gate', 'Permission Gate', ['permission-gate', 'main-skill', 'state-write']);
  }
  if (nodeIds.has('review-loop')) {
    addComposite('review-loop', 'Review Loop', ['main-skill', 'review-loop', 'state-write']);
    addComposite('ralph-loop', 'Ralph Loop', ['review-loop', 'state-write', 'post-tool-use']);
  }
  if (nodeIds.has('mcp-server')) {
    addComposite('mcp-registration', '3-Tier MCP Registration', ['permission-gate', 'mcp-server', 'post-tool-use']);
  }
  if (nodeIds.has('state-write')) {
    addComposite('lore-memory-persist', 'Lore/Memory Persist', ['main-skill', 'state-write', 'post-tool-use']);
  }
  if (customBlocks.length > 0 && nodeIds.has('custom-block')) {
    addComposite('evolutionary-seed', 'Evolutionary Seed', ['custom-block', 'main-skill', 'post-tool-use']);
  }

  return composites;
}

export function refreshDerivedProject(project: HarnessProject): HarnessProject {
  const confirmationRequests = detectConfirmationRequests(project.manifest.prompt.toLowerCase());
  return {
    ...project,
    composites: createCompositeInstances(project.nodes, project.customBlocks),
    authoring: createAuthoringDecision(project.manifest.prompt, project.nodes, confirmationRequests, project.customBlocks, project.manifest.targetRuntime)
  };
}

export function applyRiskConfirmations(project: HarnessProject, confirmed: boolean): HarnessProject {
  return {
    ...project,
    authoring: {
      ...project.authoring,
      confirmationRequests: project.authoring.confirmationRequests.map((request) => ({
        ...request,
        confirmed
      }))
    }
  };
}

function pushNode(nodes: GraphNode[], kind: GraphNode['kind'], label: string, config?: Record<string, unknown>) {
  const id = `${kind.toLowerCase()}-${nodes.length + 1}`;
  nodes.push({ id, kind, label, config });
  return id;
}

function attach(edges: GraphEdge[], from: string, to: string, label?: string) {
  edges.push({ id: `edge-${edges.length + 1}`, from, to, label });
}

export function generateHarnessProject(name: string, prompt: string, targetRuntime: RuntimeTarget = 'claude-code'): HarnessProject {
  const normalized = prompt.toLowerCase();
  const customBlocks = createCustomBlocks(normalized);
  const confirmationRequests = detectConfirmationRequests(normalized);
  const nodes: GraphNode[] = [];
  const edges: GraphEdge[] = [];

  const sessionStart = pushNode(nodes, 'SessionStart', 'Session Start');
  pushNode(nodes, 'SystemPrompt', 'System Prompt Guardrails');
  const userSubmit = pushNode(nodes, 'UserPromptSubmit', 'User Prompt Submit');
  const sequence = pushNode(nodes, 'Sequence', 'Primary Flow');
  pushNode(nodes, 'PreToolUse', 'Pre Tool Use');
  const mainSkill = 'main-skill';
  nodes.push({ id: mainSkill, kind: 'Skill', label: 'Generate Harness Skeleton', config: { skillId: 'skill-main' } });

  attach(edges, sessionStart, userSubmit);
  attach(edges, userSubmit, mainSkill);
  attach(edges, mainSkill, sequence);

  if (hasAny(normalized, ['approval', 'approve', 'permission', '권한', '승인'])) {
    const permissionId = 'permission-gate';
    nodes.push({ id: permissionId, kind: 'Permission', label: 'Permission Gate' });
    attach(edges, mainSkill, permissionId, 'requires-review');
    attach(edges, permissionId, sequence, 'approved');
  }

  if (hasAny(normalized, ['mcp', 'server', 'tool', '도구', '서버'])) {
    const mcpId = 'mcp-server';
    nodes.push({ id: mcpId, kind: 'MCPServer', label: 'MCP Server Registration' });
    attach(edges, sequence, mcpId, 'register-mcp');
  }

  if (hasAny(normalized, ['retry', 'loop', 'review', '검토', '반복'])) {
    const loopId = 'review-loop';
    nodes.push({ id: loopId, kind: 'Loop', label: 'Review Loop' });
    attach(edges, sequence, loopId, 'review');
    attach(edges, loopId, sequence, 'retry');
  }

  if (hasAny(normalized, ['state', 'memory', '기억', '상태'])) {
    nodes.push({ id: 'state-read', kind: 'StateRead', label: 'Read Existing State' });
  }

  if (customBlocks.length > 0) {
    nodes.push({
      id: 'custom-block',
      kind: 'CustomBlock',
      label: 'Novel Runtime Block',
      config: { customBlockId: customBlocks[0].id }
    });
    attach(edges, mainSkill, 'custom-block', 'extend-runtime');
    attach(edges, 'custom-block', sequence, 'runtime-generated');
  }

  nodes.push({ id: 'state-write', kind: 'StateWrite', label: 'Persist State' });
  nodes.push({ id: 'post-tool-use', kind: 'PostToolUse', label: 'Post Tool Use' });
  nodes.push({ id: 'stop', kind: 'Stop', label: 'Stop' });

  attach(edges, sequence, 'state-write', 'persist-state');
  attach(edges, 'state-write', 'post-tool-use', 'state-ready');
  attach(edges, 'post-tool-use', 'stop', 'complete');

  const layout: LayoutNode[] = nodes.map((node, index) => ({
    id: node.id,
    x: 80 + (index % 4) * 220,
    y: 120 + Math.floor(index / 4) * 160
  }));

  const authoring = createAuthoringDecision(prompt, nodes, confirmationRequests, customBlocks, targetRuntime);
  const skill = createSkill(prompt, name, authoring.warnings, targetRuntime);

  return {
    manifest: {
      name,
      version: '0.1.0',
      description: `Harness project for: ${prompt}`,
      targetRuntime,
      supportedRuntimes: [targetRuntime],
      createdAt: new Date().toISOString(),
      prompt
    },
    nodes,
    edges,
    skills: [skill],
    layout,
    composites: createCompositeInstances(nodes, customBlocks),
    customBlocks,
    registry: createRegistrySnapshot(),
    authoring
  };
}
