import type { TraceEvent } from '../core/types';

export function renderTraceHtml(projectName: string, events: TraceEvent[]): string {
  const rows = events
    .map(
      (event) => `<tr><td>${event.timestamp}</td><td>${event.hook}</td><td>${event.nodeId}</td><td>${event.status}</td><td>${event.message}</td></tr>`
    )
    .join('');

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${projectName} trace</title>
    <style>
      body { font-family: ui-sans-serif, system-ui, sans-serif; padding: 24px; background: #0b1020; color: #f3f4f6; }
      .pulse { display: inline-block; width: 12px; height: 12px; margin-right: 8px; border-radius: 999px; background: #22c55e; box-shadow: 0 0 12px #22c55e; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      td, th { border: 1px solid #334155; padding: 8px; text-align: left; }
      th { background: #111827; }
      tr:nth-child(even) { background: #111827; }
    </style>
  </head>
  <body>
    <h1><span class="pulse"></span>${projectName} Runtime Trace</h1>
    <p>Generated by Harness Editor sandbox validation.</p>
    <table>
      <thead>
        <tr><th>Timestamp</th><th>Hook</th><th>Node</th><th>Status</th><th>Message</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  </body>
</html>`;
}
