import type { TraceEvent } from '../core/types';

type TraceRecord = TraceEvent & Record<string, unknown>;

const DEFAULT_COLUMNS = new Set(['timestamp', 'eventType', 'hook', 'nodeId', 'status', 'message']);

function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function renderDetails(event: TraceRecord): string {
  const details = Object.fromEntries(Object.entries(event).filter(([key, value]) => !DEFAULT_COLUMNS.has(key) && value !== undefined && value !== ''));
  if (Object.keys(details).length === 0) return '<span class="muted">—</span>';
  return `<pre>${escapeHtml(JSON.stringify(details, null, 2))}</pre>`;
}

export function renderTraceHtml(projectName: string, events: TraceEvent[]): string {
  const rows = events
    .map(
      (event) =>
        `<tr><td>${event.timestamp}</td><td>${event.eventType}</td><td>${event.hook}</td><td>${event.nodeId}</td><td>${event.status}</td><td>${event.message}</td></tr>`
    )
    .join('');

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(projectName)} trace</title>
    <style>
      :root { color-scheme: dark; }
      body { font-family: ui-sans-serif, system-ui, sans-serif; padding: 24px; background: #0b1020; color: #f3f4f6; }
      .header { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }
      .pulse { display: inline-block; width: 12px; height: 12px; border-radius: 999px; background: #22c55e; box-shadow: 0 0 12px #22c55e; }
      .summary { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 12px; margin: 20px 0; }
      .card { border: 1px solid #334155; border-radius: 12px; padding: 16px; background: rgba(15, 23, 42, 0.8); }
      .card strong { display: block; font-size: 1.4rem; margin-top: 8px; }
      .chips { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; }
      .chip { border: 1px solid #475569; border-radius: 999px; padding: 4px 10px; font-size: 0.875rem; color: #cbd5e1; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      td, th { border: 1px solid #334155; padding: 8px; text-align: left; vertical-align: top; }
      th { background: #111827; }
      tr:nth-child(even) { background: #111827; }
      tr.is-error { background: rgba(127, 29, 29, 0.45); }
      tr.is-ok { background: rgba(15, 23, 42, 0.65); }
      pre { margin: 0; white-space: pre-wrap; word-break: break-word; font-size: 0.8rem; }
      .muted { color: #94a3b8; }
    </style>
  </head>
  <body>
    <div class="header">
      <span class="pulse"></span>
      <div>
        <h1>${escapeHtml(projectName)} Runtime Trace</h1>
        <p>Generated by Harness Editor sandbox validation.</p>
      </div>
    </div>

    <section class="summary">
      <div class="card"><span>Total events</span><strong>${traceEvents.length}</strong></div>
      <div class="card"><span>Successful events</span><strong>${okCount}</strong></div>
      <div class="card"><span>Error events</span><strong>${errorCount}</strong></div>
    </section>

    <section>
      <h2>Event types</h2>
      <div class="chips">${eventTypes.length ? eventTypes.map((eventType) => `<span class="chip">${escapeHtml(eventType)}</span>`).join('') : '<span class="muted">No event types recorded.</span>'}</div>
    </section>

    <table>
      <thead>
        <tr><th>Timestamp</th><th>Event</th><th>Hook</th><th>Node</th><th>Status</th><th>Message</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  </body>
</html>`;
}
